### ISSUE TITLE
this could cause a bug that  cannot find device

### ISSUE THREAD

**Issue by Federau** [Apollo3zehn/EtherCAT.NET#59]
![image](https://user-images.githubusercontent.com/24996986/108317915-f9ff8500-71f9-11eb-941c-6bf62ac3c2d3.png)
if product code or revision code  is larger than int.MaxValue ,then we could not find the device , casting calculated value to uint type maybe is better!

**Comment by Apollo3zehn** [comment]
Thank you, did this happen or could this happen? 
I have changed this now in the dev branch.

**Comment by Federau** [comment]
It already happened~!~
