### ISSUE TITLE
compile source code error

### ISSUE THREAD

**Issue by CN-BR-Soft** [Apollo3zehn/EtherCAT.NET#63]
**Hi,
 there is error happened when  i run .\init_solution.ps1 this command. would you like to tell me why? thanks.**

![image](https://user-images.githubusercontent.com/74814021/120774917-51c9be00-c555-11eb-80e2-e3c6d6fe93a7.png)

PS D:\Ethercat\EtherCAT.NET> .\init_solution.ps1
Updating Git submodule.
Creating native x86 project.

    目录: D:\Ethercat\EtherCAT.NET\artifacts

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----   2021/6/4 星期五     16:37                bin32
System.PlatformNotSupportedException
所在位置 D:\Ethercat\EtherCAT.NET\init_solution.ps1:25 字符: 5
+     throw [System.PlatformNotSupportedException]
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (System.PlatformNotSupportedException:RuntimeType) [], RuntimeExceptio
   n
    + FullyQualifiedErrorId : System.PlatformNotSupportedException

OS: win10 64bit
VS2019
.net core3.1

**Comment by CN-BR-Soft** [comment]
![image](https://user-images.githubusercontent.com/74814021/120774830-3ced2a80-c555-11eb-8ebe-11ebb91b5b8f.png)

**Comment by Apollo3zehn** [comment]
Hi, this looks strange. I will have a look into this in Monday.

**Comment by Apollo3zehn** [comment]
You need to use Powershell Core (i.e. Powershell 7), or edit the script and set `$IsWindows = $true`.
