### ISSUE TITLE
No action for DigitalOut.SetChannel(int channel, bool value) when channel ≥9 and ≤16

### ISSUE THREAD

**Issue by qinglingzhiqing** [Apollo3zehn/EtherCAT.NET#76]
Thanks for authors, this project is great!

Maybe there is something wrong in class DigitalOut and DigitalInt as the topic said.

I develop a project with EL2809 which has 16 digital output channels, but DigitalOut.SetChannel and DigitalOut.GetChannel didn't work when channel ≥9 and ≤16.

I check the code, find the value actually be get/set through _memoryMapping which initialized by:

```
            var channel1Pdo = _slavePdos[0];
            var variableCh1 = channel1Pdo.Variables.First();
            // get memory address of outputs
            _memoryMapping = (int*)variableCh1.DataPtr.ToPointer();
```
but the variable.DataPtr is different for channel≤8 with channel ≥9.
Thanks for your attention.

**Comment by Apollo3zehn** [comment]
Hi, thanks for your report. Please see #74 , there we already try to fix that issue.
